ssl = required
ssl_cert = </etc/ssl/ewomail/fullchain.pem
ssl_key  = </etc/ssl/ewomail/private/privkey.pem
ssl_dh   = </etc/ssl/ewomail/dh.pem
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
