plugin {
    sieve = file:~/sieve;active=~/.dovecot.sieve
    sieve_default = /ewomail/mail/sieve/default.sieve
    sieve_default_name = roundcube
    sieve_quota_max_scripts = 32
    sieve_quota_max_storage = 5M
}
