[Definition]
failregex = ^.*postfix\/smtpd\[\d+\]: NOQUEUE: reject:.+from <HOST>:.+$
            ^.*postfix\/smtpd\[\d+\]: warning: \S+\[<HOST>\]: SASL (?:LOGIN|PLAIN) authentication failed.*$
ignoreregex =
journalmatch = _SYSTEMD_UNIT=postfix@-.service
